# Fix PALLY DUTH (WB 41K 3344) wrong origin.
# User-verified: this bus does NOT serve Mejia at all - it runs
# Sonamukhi -> Kankardanga -> Rasulpur -> Khandaghosh -> Bardhaman ->
# Dankuni -> Dakshineswar -> Dunlop -> Dum Dum Airport -> Karunamoyee.
# The stoppage chain was already correct (starts at Sonamukhi 5:30 AM);
# only the origin field was wrongly "Mejia", which made the site show
# "Mejia -> Karunamoyee" and put the bus on the Mejia via-page.
# Fix: origin Mejia -> Sonamukhi. Route pages / stand pages / via pages /
# client data are regenerated by the workflow (gen_route_v2 --all etc.).
# Also: add the new sonamukhi-to-karunamoyee URL to sitemap.xml
# (route --all does not touch the main sitemap).
# Backslash-free source; string ops only; idempotent.

import datetime

DATA = 'data/busjatri_data.json'
SITEMAP = 'sitemap.xml'

REG = '"reg_no": "WB41K3344"'
OLD = '"origin": "Mejia"'
NEW = '"origin": "Sonamukhi"'


def patch_data():
    with open(DATA, encoding='utf-8') as fh:
        s = fh.read()
    i = s.find(REG)
    if i < 0:
        raise SystemExit('reg no not found - ABORT')
    j = s.find(OLD, i)
    k = s.find(NEW, i)
    if 0 <= k < i + 500:
        print('data: origin already Sonamukhi')
        return
    if j < 0 or j > i + 500:
        raise SystemExit('origin field not found near reg no - ABORT')
    s = s[:j] + NEW + s[j + len(OLD):]
    with open(DATA, 'w', encoding='utf-8') as fh:
        fh.write(s)
    print('data: origin Mejia -> Sonamukhi for WB41K3344 (PALLY DUTH)')


def patch_sitemap():
    with open(SITEMAP, encoding='utf-8') as fh:
        s = fh.read()
    if 'sonamukhi-to-karunamoyee' in s:
        print('sitemap: already present')
        return
    today = datetime.date.today().isoformat()
    url = ('<url><loc>https://busjatri.in/bus-time-table/'
           'sonamukhi-to-karunamoyee.html</loc><lastmod>' + today +
           '</lastmod><priority>0.7</priority></url>')
    marker = '</urlset>'
    i = s.find(marker)
    if i < 0:
        raise SystemExit('sitemap urlset close not found - ABORT')
    s = s[:i] + url + s[i:]
    with open(SITEMAP, 'w', encoding='utf-8') as fh:
        fh.write(s)
    print('sitemap: added sonamukhi-to-karunamoyee')


def main():
    patch_data()
    patch_sitemap()
    print('done')


if __name__ == '__main__':
    main()
