#!/usr/bin/env python3
"""
2026-09-25 patch: stop mid-word place matches leaking onto route pages.

Bug (found on busjatri.in/bus-time-table/burdwan-to-agra.html): the page
listed 10 buses, but only 1 actually runs Burdwan -> Agra (Shyamoli 7:20 PM).
The other 9 came from substring matching: the query "agra" was matching the
INSIDE of stop names like Debagram, Magra, Sagrai, Banbagram, Prayagraj -
all places around Bardhaman. Any bus passing Bardhaman + one of those stops
was pulled onto the Agra page as a "through service".

Fix: in gen_route_v2._pm_core_strict (the matcher used ONLY for static
route/stand pages - the homepage search keeps its own fuzzy matcher):
  1. substring tier now requires a WHOLE WORD (token) match, so
     "agra" no longer matches "Debagram" / "Magra" / "Banbagram";
  2. compact tier is exact-equality only (was "contains");
  3. skeleton prefix tier unchanged (already strict).

Simulation before/after: Burdwan->Agra 10 -> 1 bus (correct), while
Kolkata->Digha 126 -> 126, Esplanade->Digha 91 -> 91, Durgapur->Asansol
165 -> 165, Bardhaman->Katwa 2 -> 2, Kolkata->Beldanga 43 -> 43 unchanged.

gen_stand_v2 also imports place_matches_strict, so stand pages are
regenerated by the companion workflow too for consistency.

Idempotent: safe to run twice. Backslash-free source.
"""

import ast
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

REL = 'scripts/gen_route_v2.py'

OLD_FUNC = '''def _pm_core_strict(v, q):
    """Like _pm_core but the skeleton tier only accepts a shared PREFIX
    (same word, spelling variant). Search-style 'contains' skeletons let
    Santipur match Aantpur — wrong for a static route page."""
    if not v or not q:
        return False
    if q in v:
        return True
    vc = _re.sub(r'[^a-z0-9]', '', v)
    qc = _re.sub(r'[^a-z0-9]', '', q)
    if vc.endswith('ac'):
        vc = vc[:-2]
    if qc.endswith('ac'):
        qc = qc[:-2]
    if qc and (vc == qc or qc in vc):
        return True
    vs = _re.sub(r'[^bcdfghjklmnpqrstvwxyz]', '', v)
    qs = _re.sub(r'[^bcdfghjklmnpqrstvwxyz]', '', q)
    if len(qs) >= 4 and (vs == qs or vs.startswith(qs)):
        return True
    return False
'''

NEW_FUNC = '''def _pm_word(v, q):
    """Whole-word (token) containment: the query must appear in the value
    as one or more complete words - never glued inside another word.
    So "agra" matches "Agra" / "Agra Cantt" but NOT "Debagram" / "Magra" /
    "Sagrai" / "Banbagram" / "Prayagraj"."""
    vt = [t for t in _re.split('[^a-z0-9]+', v) if t]
    qt = [t for t in _re.split('[^a-z0-9]+', q) if t]
    if not vt or not qt:
        return False
    n = len(qt)
    for i in range(len(vt) - n + 1):
        if vt[i:i + n] == qt:
            return True
    return False

def _pm_core_strict(v, q):
    """Strict matcher for STATIC route/stand pages (2026-09-25): substring
    tier accepts whole words only (Agra no longer matches Debagram or Magra),
    compact tier is exact equality, and the skeleton tier only accepts a
    shared PREFIX (Santipur vs Aantpur). The homepage search keeps the
    looser place_matches() - this strict path is for page generation."""
    if not v or not q:
        return False
    if v == q:
        return True
    if _pm_word(v, q):
        return True
    vc = _re.sub(r'[^a-z0-9]', '', v)
    qc = _re.sub(r'[^a-z0-9]', '', q)
    if vc.endswith('ac'):
        vc = vc[:-2]
    if qc.endswith('ac'):
        qc = qc[:-2]
    if qc and vc == qc:
        return True
    vs = _re.sub(r'[^bcdfghjklmnpqrstvwxyz]', '', v)
    qs = _re.sub(r'[^bcdfghjklmnpqrstvwxyz]', '', q)
    if len(qs) >= 4 and (vs == qs or vs.startswith(qs)):
        return True
    return False
'''

def read(rel):
    with open(os.path.join(ROOT, rel), encoding='utf-8') as fh:
        return fh.read()

src = read(REL)

if '_pm_word' in src:
    print('SKIP', REL, '(already patched)')
else:
    assert OLD_FUNC in src, 'gen_route_v2.py: _pm_core_strict block not found verbatim'
    src = src.replace(OLD_FUNC, NEW_FUNC)
    with open(os.path.join(ROOT, REL), 'w', encoding='utf-8') as fh:
        fh.write(src)
    print('PATCHED', REL)

# ------------------------------------------------------------ validate ----
errors = []

txt = read(REL)
if '_pm_word' not in txt:
    errors.append('new _pm_word helper missing')
if txt.count('if q in v:') != 1:
    errors.append('substring tier not removed from strict matcher (count of "if q in v:" should be 1, got %d)' % txt.count('if q in v:'))
if 'if qc and (vc == qc or qc in vc):' in txt.split('def _pm_core_strict')[1].split('def ')[0]:
    errors.append('compact containment still present in strict matcher')

try:
    ast.parse(txt)
except SyntaxError as e:
    errors.append('syntax error: ' + str(e))

# behavioural spot-checks: import the module and test the new matcher
sys.path.insert(0, os.path.join(ROOT, 'scripts'))
os.chdir(ROOT)
import gen_route_v2 as v2

CASES = [
    ('magra', 'agra', False), ('debagram', 'agra', False),
    ('sagrai', 'agra', False), ('banbagram', 'agra', False),
    ('prayagraj', 'agra', False), ('khagraghat', 'agra', False),
    ('agra', 'agra', True), ('Agra Cantt', 'agra', True),
    ('kolkata (esplanade)', 'esplanade', True), ('garia bus stand', 'garia', True),
    ('burdwan bypass', 'burdwan', True), ('new digha', 'digha', True),
]
for value, query, want in CASES:
    got = v2.place_matches_strict(value, query)
    if got != want:
        errors.append('matcher: place_matches_strict(%r, %r) = %r, want %r' % (value, query, got, want))

if errors:
    print('VALIDATION FAILED:')
    for e in errors:
        print('  -', e)
    sys.exit(1)

print('VALIDATION OK (all spot-checks pass)')
