#!/usr/bin/env python3
"""FB community batch 4 (2026-09-18 late evening) - 4 pastes compiled.

NEW buses (8):
  1. RBN TRAVELS Kharagpur-Barabazar (WB 55B 7065)
  2. MAA PARUL (Maa Santoshi) Jayrambati-Durgapur (WB 67 3747)
  3. SAMRAT Bolpur-Suri-Dumka (WB 53C 5564)
  4. MAHAMAYA (STA) Kolkata Station-Manbazar (WB 29E 4991 & 4954)
  5. LALKAMAL Kharagpur-Manbazar (WB 33L 8127)
  6. EXPRESS LINE Kolkata-Bangalore Volvo AC Sleeper (WB 11K 6999)
  7. ISHIKA TRADERS Asansol-Digha 2x2 AC Sleeper (WB 41K 2500 & 2452)
  8. PROMILA Bolpur-Barakar (WB 53B 5780)

UPDATES (8, reg/time match):
  SANNYASI (684), MONAMI new route (507), MITRA (502),
  RUDRAPRIYA (907), CHENNAI EXPRESS (165), JINIA night AC
  (wbbustime-jinia-0), KALOSONA (1331), MAA TARA/RUDRAYANI (441)

DELETES (2): bussathi-maa-rudrayani-424, wbbustime-ma-tara-ma-rudrayani-ac-0
(same Medinipur-Mayapur AC duo service as 441)

SKIP: RBN + MAA TARA duplicate posts, SRI KRISHNA (already complete).

Idempotent: re-running makes no changes.
"""
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DRY = "--write" not in sys.argv


def st(*rows):
    return [{"name": n, "up": u, "down": d} for n, u, d in rows]


def sp(*rows):
    return [{"no": i + 1, "name": n, "up_time": u, "down_time": d} for i, (n, u, d) in enumerate(rows)]


NEW_BUSES = [
    {
        "operator": "RBN Travels",
        "bus_name": "RBN Travels Kharagpur-Barabazar",
        "bus_type": "Private",
        "reg_no": "WB 55B 7065",
        "origin": "Kharagpur",
        "destination": "Barabazar",
        "departure_time": "4:40 AM",
        "arrival_time": "11:20 AM",
        "route": "Kharagpur - Barabazar",
        "source": "facebook (community report)",
        "detail_url": "",
        "contact_number": "7584871470",
        "stops": st(
            ("Kharagpur Station", "4:40 AM", "8:00 PM"),
            ("Chowringhee", "4:50 AM", "7:50 PM"),
            ("Lodhashuli", "5:40 AM", "6:55 PM"),
            ("Jhargram Central Bus Stand", "6:20 AM", ""),
            ("Jhargram Panch Mathar More", "", "6:30 PM"),
            ("Binpur", "7:00 AM", "5:55 PM"),
            ("Shilda", "7:30 AM", "5:35 PM"),
            ("Fulkusma", "7:55 AM", "5:05 PM"),
            ("Raipur", "8:20 AM", "4:30 PM"),
            ("Haludkanali", "", ""),
            ("Ankukhuta More", "9:00 AM", "3:30 PM"),
            ("Khatra", "9:20 AM", "3:05 PM"),
            ("Hatirampur", "9:40 AM", "2:40 PM"),
            ("Payrachali", "10:00 AM", "2:15 PM"),
            ("Manbazar", "10:20 AM", "1:45 PM"),
            ("Sindri", "10:50 AM", "1:10 PM"),
            ("Barabazar", "11:20 AM", "12:45 PM"),
        ),
    },
    {
        "operator": "Maa Parul (Maa Santoshi)",
        "bus_name": "Maa Parul Jayrambati-Durgapur",
        "bus_type": "Private",
        "reg_no": "WB 67 3747",
        "origin": "Jayrambati",
        "destination": "Durgapur",
        "departure_time": "4:30 AM",
        "arrival_time": "9:55 AM",
        "route": "Jayrambati - Durgapur",
        "source": "facebook (community report)",
        "detail_url": "",
        "contact_number": "",
        "stops": st(
            ("Jayrambati", "4:30 AM", "5:45 PM"),
            ("Ramdiha", "4:50 AM", "5:30 PM"),
            ("Kuchakol", "", ""),
            ("Moynapur", "5:15 AM", "4:40 PM"),
            ("Jaypur", "5:35 AM", "4:25 PM"),
            ("Bishnupur", "6:20 AM", "3:40 PM"),
            ("Ramsagar", "", ""),
            ("Onda", "", ""),
            ("Kalisen", "", ""),
            ("Dholdanga", "", ""),
            ("Bankura", "8:10 AM", "2:10 PM"),
            ("Hevry More", "", ""),
            ("Bikna", "", ""),
            ("Beliatore", "", ""),
            ("Barjora", "", ""),
            ("Durgapur Station", "9:55 AM", "11:40 AM"),
        ),
    },
    {
        "operator": "Samrat",
        "bus_name": "Samrat Bolpur-Suri-Dumka (Priti Coach)",
        "bus_type": "Private",
        "reg_no": "WB 53C 5564",
        "origin": "Bolpur",
        "destination": "Dumka",
        "departure_time": "6:50 AM",
        "arrival_time": "10:40 AM",
        "route": "Bolpur - Suri - Dumka",
        "source": "facebook (community report)",
        "detail_url": "",
        "contact_number": "9294700029, 9933178823, 6294700092",
        "stops": st(
            ("Bolpur (Jambuni)", "6:50 AM", "3:30 PM"),
            ("Sriniketan", "", ""),
            ("Debgram", "", ""),
            ("Pandui", "7:30 AM", "3:10 PM"),
            ("Purandpur", "7:45 AM", "2:50 PM"),
            ("Suri", "8:15 AM", "2:30 PM"),
            ("Tilpara Barrage", "", ""),
            ("Khoyrakuri", "", ""),
            ("Shyorakuri", "8:45 AM", "1:55 PM"),
            ("Hingla", "", ""),
            ("Sukjora", "", ""),
            ("Ranishwar", "9:15 AM", "1:30 PM"),
            ("Kumirdah", "", ""),
            ("Ranibahal", "9:40 AM", "1:05 PM"),
            ("Nadatala", "", ""),
            ("Massanjore", "9:50 AM", "12:55 PM"),
            ("Jitpur", "", ""),
            ("Chaklota", "", ""),
            ("Indrabani", "", ""),
            ("Patabari", "10:15 AM", "12:45 PM"),
            ("Katijdiya", "", ""),
            ("Karmatar", "", ""),
            ("Gidhni Pahar", "", ""),
            ("Dumka", "10:40 AM", "11:45 AM"),
        ),
    },
    {
        "operator": "Mahamaya (STA Super Fast)",
        "bus_name": "Mahamaya Kolkata Station-Manbazar (STA Super Fast)",
        "bus_type": "Private",
        "reg_no": "WB 29E 4991 & WB 29E 4954",
        "origin": "Kolkata (Station)",
        "destination": "Manbazar",
        "departure_time": "4:30 AM",
        "arrival_time": "12:10 PM",
        "route": "Kolkata Station - Manbazar",
        "source": "facebook (community report)",
        "detail_url": "",
        "contact_number": "9474154532",
        "stops": st(
            ("Kolkata Station", "4:30 AM", "5:50 PM"),
            ("Shyambazar", "4:40 AM", "5:40 PM"),
            ("Chiria More", "", ""),
            ("Sinthi More", "", ""),
            ("Baranagar", "", ""),
            ("Dunlop", "4:57 AM", "5:30 PM"),
            ("Dakshineswar", "", ""),
            ("Bali Halt", "5:05 AM", "5:20 PM"),
            ("Dankuni", "5:20 AM", "5:10 PM"),
            ("Chanditala", "5:30 AM", "5:05 PM"),
            ("Mashat", "", ""),
            ("Siyakhala", "5:45 AM", "4:45 PM"),
            ("Gajar More", "", ""),
            ("Champadanga", "6:20 AM", "4:10 PM"),
            ("Sodepur", "", ""),
            ("Arambagh", "7:20 AM", "3:25 PM"),
            ("Bengai", "", ""),
            ("Khatul", "", ""),
            ("Kotulpur", "8:05 AM", "2:30 PM"),
            ("Jaypur", "", ""),
            ("Bishnupur", "9:15 AM", "1:25 PM"),
            ("Ramsagar", "", ""),
            ("Onda", "", ""),
            ("Dholdanga More", "", ""),
            ("Bankura Bypass", "", ""),
            ("Tamlibandh", "", ""),
            ("Bankura Pump More", "10:50 AM", "11:55 AM"),
            ("Shunukpahari", "11:00 AM", "11:30 AM"),
            ("Puabagan", "", ""),
            ("Bangla", "11:15 AM", "11:15 AM"),
            ("Molian", "11:35 AM", "10:55 AM"),
            ("Gadapathar", "", ""),
            ("Payrachali", "11:55 AM", "10:35 AM"),
            ("Manbazar", "12:10 PM", "10:20 AM"),
        ),
    },
    {
        "operator": "Lalkamal",
        "bus_name": "Lalkamal Kharagpur-Manbazar (Super Fast)",
        "bus_type": "Private",
        "reg_no": "WB 33L 8127",
        "origin": "Kharagpur",
        "destination": "Manbazar",
        "departure_time": "4:20 AM",
        "arrival_time": "9:00 AM",
        "route": "Kharagpur - Medinipur - Manbazar",
        "source": "facebook (community report)",
        "detail_url": "",
        "contact_number": "9749595372",
        "stops": st(
            ("Kharagpur", "4:20 AM", "2:40 PM"),
            ("Chowringhee", "", ""),
            ("Medinipur", "4:55 AM", "2:00 PM"),
            ("Bhadutala", "", ""),
            ("Moupal", "", ""),
            ("Pirakata", "", "12:55 PM"),
            ("Sijua", "", ""),
            ("Goaltore", "6:20 AM", "12:20 PM"),
            ("Pingbani", "", ""),
            ("Sarenga", "6:50 AM", "11:45 AM"),
            ("P. More", "7:05 AM", "11:25 AM"),
            ("Raipur", "7:15 AM", "11:10 AM"),
            ("Ankukhuta More", "", ""),
            ("Khatra", "8:05 AM", "10:25 AM"),
            ("Hatirampur", "8:20 AM", "10:05 AM"),
            ("Payrachali", "8:45 AM", "9:35 AM"),
            ("Manbazar", "9:00 AM", "9:25 AM"),
        ),
    },
    {
        "operator": "Express Line",
        "bus_name": "Express Line Kolkata-Bangalore (Volvo AC Sleeper)",
        "bus_type": "Private - Interstate AC Sleeper",
        "reg_no": "WB 11K 6999",
        "origin": "Kolkata (Karunamoyee)",
        "destination": "Bangalore",
        "departure_time": "5:30 PM",
        "arrival_time": "8:20 AM (2nd day)",
        "route": "Kolkata - Kharagpur - Bhubaneswar - Visakhapatnam - Tirupati - Bangalore",
        "source": "facebook (community report)",
        "detail_url": "",
        "contact_number": "9088900002, 9088900003, 9088811120",
        "stops": st(
            ("Kolkata (Karunamoyee)", "5:30 PM", ""),
            ("Dharmatala", "7:30 PM", "6:45 AM"),
            ("Santragachi", "7:45 PM", ""),
            ("Kharagpur Bypass", "10:30 PM", ""),
            ("Baleswar", "", ""),
            ("Bhadrak", "", ""),
            ("Cuttack", "", ""),
            ("Bhubaneswar", "5:30 AM", "9:45 PM"),
            ("Berhampur", "", ""),
            ("Sompeta", "", ""),
            ("Ichchapuram", "", ""),
            ("Srikakulam", "", ""),
            ("Vizianagaram", "", ""),
            ("Visakhapatnam", "", "3:25 PM"),
            ("Tallapalem", "", ""),
            ("Nakkapali", "", ""),
            ("Jaggampeta", "", ""),
            ("Rajanagar", "", ""),
            ("Rajahmundry", "4:59 PM", ""),
            ("Ananthapalli", "", ""),
            ("Eluru", "", ""),
            ("Vijayawada", "", ""),
            ("Guntur", "", ""),
            ("Ongole", "", ""),
            ("Nellore", "", ""),
            ("Renigunta", "", ""),
            ("Tirupati", "", "3:00 AM"),
            ("Chittoor", "", ""),
            ("Bangalore (Attibele)", "8:20 AM", "7:45 PM"),
            ("Chandpura", "", "8:30 PM"),
            ("Bommasandra", "", "8:45 PM"),
            ("Electronic City", "", "9:10 PM"),
        ),
    },
    {
        "operator": "Ishika Traders",
        "bus_name": "Ishika Traders Asansol-Digha (AC Sleeper)",
        "bus_type": "Private - AC Sleeper (2x2)",
        "reg_no": "WB 41K 2500 & WB 41K 2452",
        "origin": "Asansol",
        "destination": "Digha",
        "departure_time": "8:00 PM",
        "arrival_time": "5:00 AM",
        "route": "Asansol - Medinipur - Digha",
        "source": "facebook (community report)",
        "detail_url": "",
        "contact_number": "7699995927, 9749437344",
        "stops": st(
            ("Asansol", "8:00 PM", "6:20 PM"),
            ("Raniganj", "", ""),
            ("Durgapur (City Center)", "", "5:20 PM"),
            ("Durgapur (Station)", "9:20 PM", "5:00 PM"),
            ("Barjora", "", ""),
            ("Beliatore", "", ""),
            ("Bankura Bypass", "10:20 PM", "4:00 PM"),
            ("Dholdanga", "", ""),
            ("Onda", "", ""),
            ("Ramsagar", "11:30 PM", ""),
            ("Bishnupur", "", "3:00 PM"),
            ("Bankadah", "", ""),
            ("Dhadika", "", ""),
            ("Garhbeta", "", "2:20 PM"),
            ("Chandrakona Road", "", "2:05 PM"),
            ("Salboni", "", ""),
            ("Bhadutala", "", ""),
            ("Medinipur", "", "1:00 PM"),
            ("Kharagpur Chowringhee", "", "12:20 PM"),
            ("Kharagpur Station", "1:45 AM", ""),
            ("Makrampur", "", ""),
            ("Narayangarh", "", "11:55 AM"),
            ("Bakhra Bad", "", ""),
            ("Belda", "", "11:45 AM"),
            ("Thakurchak", "", ""),
            ("Khakurda", "", ""),
            ("Sauri", "", ""),
            ("Jahalda", "", ""),
            ("Lalat", "", ""),
            ("Egra", "", "11:15 AM"),
            ("Dobadhi", "", ""),
            ("Balighai", "", ""),
            ("Tajpur", "", ""),
            ("Bhabanichak", "", ""),
            ("Satmile", "", ""),
            ("Rautara", "", ""),
            ("Kanthi Central Bus Stand", "", "10:25 AM"),
            ("Ghatua", "", ""),
            ("Pichabani", "", ""),
            ("Chaulkhola (Mandarmani)", "", ""),
            ("Balisai (Tajpur)", "", ""),
            ("Chhodomile (Shankarpur)", "", ""),
            ("Ramnagar", "", ""),
            ("Thikra More", "", ""),
            ("Old Digha", "", ""),
            ("New Digha", "", ""),
            ("Digha", "5:00 AM", "9:10 AM"),
        ),
    },
    {
        "operator": "Promila",
        "bus_name": "Promila Bolpur-Barakar",
        "bus_type": "Private",
        "reg_no": "WB 53B 5780",
        "origin": "Bolpur",
        "destination": "Barakar",
        "departure_time": "6:20 AM",
        "arrival_time": "10:15 AM",
        "route": "Bolpur - Ilambazar - Panagarh - Durgapur - Asansol - Barakar",
        "source": "facebook (community report)",
        "detail_url": "",
        "contact_number": "",
        "stops": st(
            ("Bolpur (Jambuni)", "6:20 AM", "4:20 PM"),
            ("Suratheswar", "6:32 AM", "4:12 PM"),
            ("Ilambazar", "6:55 AM", "3:40 PM"),
            ("11 Mile", "7:10 AM", "3:30 PM"),
            ("Panagarh", "7:40 AM", "2:55 PM"),
            ("Darjiling More", "7:47 AM", "3:02 PM"),
            ("Muchipara", "8:05 AM", "2:35 PM"),
            ("Durgapur (City Center)", "8:15 AM", "2:20 PM"),
            ("Raniganj More", "8:50 AM", "1:50 PM"),
            ("Andal", "", ""),
            ("Asansol", "9:20 AM", "1:05 PM"),
            ("Barakar", "10:15 AM", "12:25 PM"),
        ),
    },
]

SANNYASI_STOPS = sp(
    ("Kultikri", "5:20 AM", "7:00 PM"),
    ("Guptamoni", "5:55 AM", "6:30 PM"),
    ("Balibhasa", "", ""),
    ("Lodhashuli", "6:25 AM", "6:10 PM"),
    ("Jitushol", "", ""),
    ("Jhargram Central Bus Stand", "6:55 AM", ""),
    ("Jhargram Panch Mathar More", "7:07 AM", "5:40 PM"),
    ("Lalgarh", "7:40 AM", "4:50 PM"),
    ("Katapahari", "", ""),
    ("Ramgarh", "8:05 AM", "4:15 PM"),
    ("Brahmandiha", "", ""),
    ("Taldiha", "", ""),
    ("Sarenga", "8:40 AM", "3:45 PM"),
    ("P. More", "9:15 AM", "3:25 PM"),
    ("Bikrampur", "9:30 AM", "3:05 PM"),
    ("Amlasuli", "", ""),
    ("Humgar", "10:20 AM", "2:15 PM"),
    ("Garhbeta", "10:55 AM", "1:45 PM"),
    ("Dhadika", "", ""),
    ("Chaubeta More", "", ""),
    ("Bankadaha", "", ""),
    ("Bishnupur", "11:35 AM", "12:50 PM"),
)

MONAMI_STOPS = sp(
    ("Jhargram", "5:00 AM", "1:25 PM"),
    ("Lalgarh", "5:30 AM", "12:45 PM"),
    ("Bakshi", "6:15 AM", "11:55 AM"),
    ("Fulkusma", "6:30 AM", "11:35 AM"),
    ("Raipur", "7:00 AM", "11:05 AM"),
    ("Haludkanali", "", ""),
    ("Ankukhuta More", "", ""),
    ("Khatra", "7:40 AM", "10:15 AM"),
    ("Hatirampur", "8:05 AM", "9:55 AM"),
    ("Payrachali", "8:30 AM", "9:35 AM"),
    ("Manbazar", "8:45 AM", "9:15 AM"),
)

MITRA_STOPS = sp(
    ("Asansol", "6:15 AM", "4:50 PM"),
    ("Raniganj", "", ""),
    ("Durgapur (City Center)", "7:15 AM", "3:30 PM"),
    ("Durgapur (Station)", "7:40 AM", "3:15 PM"),
    ("Barjora", "", ""),
    ("Beliatore", "", ""),
    ("Makurgram", "", ""),
    ("Bankura Bypass", "8:45 AM", "2:05 PM"),
    ("Dhaldanga", "", ""),
    ("Onda", "", ""),
    ("Ramsagar", "", ""),
    ("Bishnupur", "9:50 AM", "1:20 PM"),
    ("Bankadah", "10:10 AM", "12:50 PM"),
    ("Dhadika", "", ""),
    ("Garhbeta", "", "12:40 PM"),
    ("Chandrakona", "11:00 AM", "12:05 PM"),
    ("Salboni", "", ""),
    ("Bhadutala", "", ""),
    ("Medinipur", "12:20 PM", "11:00 AM"),
    ("Kharagpur", "1:20 PM", "10:00 AM"),
    ("Belda", "2:10 PM", "9:25 AM"),
    ("Egra", "2:50 PM", "8:45 AM"),
    ("Contai (Kanthi)", "3:40 PM", "8:00 AM"),
)

RUDRAPRIYA_STOPS = sp(
    ("Chandipur", "5:00 AM", "5:50 PM"),
    ("Bajkul", "5:50 AM", "5:20 PM"),
    ("Bhagwanpur", "6:20 AM", "5:00 PM"),
    ("Manglamaro", "7:10 AM", "4:25 PM"),
    ("Patashpur", "7:30 AM", "4:00 PM"),
    ("Egra", "8:05 AM", "3:25 PM"),
    ("Jahalda", "8:20 AM", ""),
    ("Khakurda", "8:45 AM", "2:30 PM"),
    ("Belda", "9:00 AM", "2:15 PM"),
    ("Kharagpur Chowringhee", "9:50 AM", "1:20 PM"),
    ("Medinipur", "10:20 AM", "12:30 PM"),
)

CHENNAI_EXPRESS_STOPS = sp(
    ("Egra", "7:10 AM", ""),
    ("Kharai More", "", ""),
    ("Patashpur", "7:35 AM", ""),
    ("Manglamaro", "8:10 AM", ""),
    ("Bhagwanpur", "8:40 AM", ""),
    ("Bajkul", "9:05 AM", ""),
    ("Chandipur", "9:20 AM", ""),
    ("Nandakumar", "9:35 AM", ""),
    ("Nimtouri", "", ""),
    ("Radhamani", "", ""),
    ("Mecheda", "", ""),
    ("Kolaghat", "", ""),
    ("Bagnan", "", ""),
    ("Kona", "", ""),
    ("Dakshineswar", "", ""),
    ("Dunlop", "", "6:15 PM"),
    ("Baranagar", "", ""),
    ("Durganagar", "", ""),
    ("Airport", "", "5:55 PM"),
    ("Kaikhali", "", ""),
    ("Haldiram", "", "5:45 PM"),
    ("Chinar Park", "", ""),
    ("Eco Park", "", ""),
    ("Narkelbagan (Biswabangla Gate)", "", ""),
    ("Newtown", "", "5:25 PM"),
    ("Technopolis", "", ""),
    ("Sector V", "", ""),
    ("College More (Karunamoyee)", "", "5:10 PM"),
)

JINIA_STOPS = sp(
    ("Asansol", "6:00 PM", "6:20 PM"),
    ("Raniganj", "", ""),
    ("Durgapur (City Center)", "7:05 PM", "5:25 PM"),
    ("Durgapur (Station)", "7:40 PM", "5:10 PM"),
    ("Barjora", "8:00 PM", "4:50 PM"),
    ("Beliatore", "", ""),
    ("Bankura Bypass", "8:40 PM", "4:10 PM"),
    ("Dholdanga", "8:50 PM", ""),
    ("Onda", "", "3:40 PM"),
    ("Ramsagar", "10:00 PM", ""),
    ("Bishnupur", "10:10 PM", "3:15 PM"),
    ("Bankadah", "10:20 PM", "2:40 PM"),
    ("Dhadika", "", ""),
    ("Garhbeta", "10:30 PM", "2:25 PM"),
    ("Chandrakona Road", "10:50 PM", "2:05 PM"),
    ("Salboni", "11:00 PM", "1:45 PM"),
    ("Bhadutala", "", ""),
    ("Medinipur", "11:40 PM", "1:00 PM"),
    ("Kharagpur Chowringhee", "", ""),
    ("Kharagpur Station", "12:20 AM", "11:45 AM"),
    ("Makrampur", "", ""),
    ("Narayangarh", "", ""),
    ("Bakhra Bad", "", ""),
    ("Belda", "1:20 AM", "10:45 AM"),
    ("Thakurchak", "", ""),
    ("Khakurda", "", ""),
    ("Sauri", "", ""),
    ("Jahalda", "", ""),
    ("Lalat", "", ""),
    ("Egra", "2:00 AM", "10:05 AM"),
    ("Dobadhi", "", ""),
    ("Balighai", "", ""),
    ("Tajpur", "", ""),
    ("Bhabanichak", "", ""),
    ("Satmile", "", ""),
    ("Rautara", "", ""),
    ("Kanthi Central Bus Stand", "2:40 AM", "9:20 AM"),
    ("Pichabani", "", ""),
    ("Chaulkhola (Mandarmani)", "", "8:50 AM"),
    ("Balisai (Tajpur)", "", ""),
    ("Chhodomile (Shankarpur)", "", ""),
    ("Ramnagar", "", "8:25 AM"),
    ("Thikra More", "", ""),
    ("Old Digha", "", ""),
    ("New Digha", "", "8:10 AM"),
    ("Digha Border", "3:40 AM", ""),
)

KALOSONA_STOPS = sp(
    ("Asansol", "8:15 PM", "7:15 PM"),
    ("Raniganj", "", ""),
    ("Durgapur (City Center)", "9:20 PM", "6:10 PM"),
    ("Durgapur (Station)", "9:30 PM", "6:00 PM"),
    ("Barjora", "", ""),
    ("Beliatore", "", ""),
    ("Bankura Bypass", "", "4:35 PM"),
    ("Dholdanga", "", ""),
    ("Onda", "", ""),
    ("Ramsagar", "", ""),
    ("Bishnupur", "", "3:45 PM"),
    ("Bankadah", "", "3:30 PM"),
    ("Dhadika", "", ""),
    ("Garhbeta", "", ""),
    ("Chandrakona Road", "", ""),
    ("Salboni", "", ""),
    ("Bhadutala", "", ""),
    ("Medinipur", "", ""),
    ("Kharagpur Chowringhee", "2:25 AM", ""),
    ("Makrampur", "", ""),
    ("Narayangarh", "", ""),
    ("Bakhra Bad", "", ""),
    ("Belda", "", ""),
    ("Thakurchak", "", ""),
    ("Khakurda", "", ""),
    ("Sauri", "", ""),
    ("Jahalda", "", ""),
    ("Lalat", "", ""),
    ("Egra", "", ""),
    ("Dobadhi", "", ""),
    ("Balighai", "", ""),
    ("Tajpur", "", ""),
    ("Bhabanichak", "", ""),
    ("Satmile", "", ""),
    ("Rautara", "", ""),
    ("Kanthi Central Bus Stand", "4:30 AM", "11:20 AM"),
    ("Pichabani", "", ""),
    ("Chaulkhola (Mandarmani)", "", ""),
    ("Balisai (Tajpur)", "", ""),
    ("Chhodomile (Shankarpur)", "", ""),
    ("Ramnagar", "", ""),
    ("Thikra More", "", ""),
    ("Old Digha", "", "10:05 AM"),
    ("New Digha", "", "10:15 AM"),
    ("Digha Border", "5:35 AM", ""),
)

MAA_TARA_STOPS = sp(
    ("Medinipur", "7:10 AM", "5:10 PM"),
    ("Mohanpur", "", ""),
    ("Chowringhee (Kharagpur)", "", ""),
    ("Madpur", "", ""),
    ("Basantpur", "", ""),
    ("Debra", "8:00 AM", "4:25 PM"),
    ("Ashari", "", ""),
    ("Ratulia", "", ""),
    ("Mechogram", "", ""),
    ("Siddha Bazar", "", ""),
    ("Deulia Bazar", "", ""),
    ("Haldia More", "", ""),
    ("Kolaghat", "8:40 AM", "3:45 PM"),
    ("Bagnan", "8:50 AM", "3:35 PM"),
    ("Uluberia", "", ""),
    ("Panchla", "", ""),
    ("Ranihati", "", ""),
    ("Dhulagarh", "", ""),
    ("Kona Expressway", "9:30 AM", "2:40 PM"),
    ("Salp", "", ""),
    ("Bali Halt", "", ""),
    ("Dakshineswar", "10:00 AM", "2:20 PM"),
    ("Dunlop", "10:10 AM", "2:15 PM"),
    ("Sodepur", "10:45 AM", ""),
    ("Barrackpore", "11:00 AM", "1:40 PM"),
    ("Naihati", "11:20 AM", "1:30 PM"),
    ("Kanchrapara", "11:25 AM", "1:25 PM"),
    ("Kalyani Bus Stand", "", ""),
    ("Kalyani AIIMS", "11:35 AM", "1:10 PM"),
    ("Chakdaha", "11:55 AM", "12:45 PM"),
    ("Ranaghat", "12:15 PM", "12:15 PM"),
    ("Krishnanagar", "12:45 PM", "11:45 AM"),
    ("Mayapur", "1:10 PM", "11:15 AM"),
)

UPDATES = [
    {
        "id": "bussathi-sannyasi-684",
        "marker": "Jitushol",
        "fields": {
            "bus_name": "SANNYASI",
            "operator": "Sannyasi",
            "bus_type": "Private",
            "origin": "Kultikri",
            "destination": "Bishnupur",
            "departure_time": "5:20 AM",
            "arrival_time": "11:35 AM",
            "contact_number": "9851105103",
            "route": "Kultikri - Jhargram - Garhbeta - Bishnupur",
            "stoppages": SANNYASI_STOPS,
            "total_stoppages": len(SANNYASI_STOPS),
        },
    },
    {
        "id": "bussathi-monami-507",
        "marker": "Bakshi",
        "fields": {
            "bus_name": "MONAMI TRAVELS",
            "operator": "Monami Travels",
            "bus_type": "Private",
            "origin": "Jhargram",
            "destination": "Manbazar",
            "departure_time": "5:00 AM",
            "arrival_time": "8:45 AM",
            "reg_no": "WB 39F 2442",
            "contact_number": "",
            "route": "Jhargram - Lalgarh - Raipur - Khatra - Manbazar",
            "stoppages": MONAMI_STOPS,
            "total_stoppages": len(MONAMI_STOPS),
        },
    },
    {
        "id": "bussathi-mitra-502",
        "marker": "Bankadah",
        "fields": {
            "bus_name": "MITRA (Super Fast)",
            "operator": "Mitra",
            "bus_type": "Private",
            "origin": "Asansol",
            "destination": "Contai (Kanthi)",
            "departure_time": "6:15 AM",
            "arrival_time": "3:40 PM",
            "contact_number": "7319325245",
            "route": "Asansol - Medinipur - Contai",
            "stoppages": MITRA_STOPS,
            "total_stoppages": len(MITRA_STOPS),
        },
    },
    {
        "id": "bussathi-rudrapriya-907",
        "marker": "Manglamaro",
        "fields": {
            "bus_name": "RUDRAPRIYA (Super Fast)",
            "operator": "Rudrapriya",
            "bus_type": "Private",
            "origin": "Chandipur",
            "destination": "Medinipur",
            "departure_time": "5:00 AM",
            "arrival_time": "10:20 AM",
            "reg_no": "WB 29B 3642",
            "contact_number": "",
            "route": "Chandipur - Belda - Medinipur",
            "stoppages": RUDRAPRIYA_STOPS,
            "total_stoppages": len(RUDRAPRIYA_STOPS),
        },
    },
    {
        "id": "bussathi-chennai-express-165",
        "marker": "Kharai More",
        "fields": {
            "bus_name": "CHENNAI EXPRESS (Maa Bipattarini / Asha Travels)",
            "operator": "Chennai Express",
            "bus_type": "Private",
            "origin": "Egra",
            "destination": "Karunamoyee",
            "departure_time": "7:10 AM",
            "arrival_time": "",
            "reg_no": "WB 29G 2073",
            "contact_number": "7363056092, 909103609",
            "route": "Egra - Mecheda - Kolkata - Karunamoyee",
            "stoppages": CHENNAI_EXPRESS_STOPS,
            "total_stoppages": len(CHENNAI_EXPRESS_STOPS),
        },
    },
    {
        "id": "wbbustime-jinia-0",
        "marker": "Dobadhi",
        "fields": {
            "bus_name": "JINIA (AC Coach - Night)",
            "operator": "Jinia",
            "bus_type": "Private - AC (Day-Night)",
            "origin": "Asansol",
            "destination": "Digha Border",
            "departure_time": "6:00 PM",
            "arrival_time": "3:40 AM",
            "reg_no": "WB 37H 9318 & WB 37L 1903",
            "contact_number": "8637850254",
            "route": "Asansol - Bishnupur - Medinipur - Digha",
            "stoppages": JINIA_STOPS,
            "total_stoppages": len(JINIA_STOPS),
        },
    },
    {
        "id": "wbbus-in-kalosona-1331",
        "marker": "Bakhra Bad",
        "fields": {
            "bus_name": "KALOSONA DREAMLINE (AC Seater/Sleeper)",
            "operator": "Kalosona Dreamline",
            "bus_type": "Private - AC Seater/Sleeper (Bio-Toilet)",
            "origin": "Asansol",
            "destination": "Digha",
            "departure_time": "8:15 PM",
            "arrival_time": "5:35 AM",
            "contact_number": "9382209568, 8653434855",
            "route": "Asansol - Kharagpur - Digha",
            "stoppages": KALOSONA_STOPS,
            "total_stoppages": len(KALOSONA_STOPS),
        },
    },
    {
        "id": "bussathi-maa-tara-441",
        "marker": "Kalyani AIIMS",
        "fields": {
            "bus_name": "MAA TARA / MAA RUDRAYANI (AC)",
            "operator": "Maa Tara / Maa Rudrayani",
            "bus_type": "Private - AC",
            "origin": "Medinipur",
            "destination": "Mayapur",
            "departure_time": "7:10 AM",
            "arrival_time": "1:10 PM",
            "reg_no": "WB 35E 2745 & WB 35E 2746",
            "contact_number": "8250206920, 9733647390, 9332418688, 8617348868",
            "route": "Medinipur - Kolkata - Mayapur",
            "stoppages": MAA_TARA_STOPS,
            "total_stoppages": len(MAA_TARA_STOPS),
        },
    },
]

DELETE_IDS = ["bussathi-maa-rudrayani-424", "wbbustime-ma-tara-ma-rudrayani-ac-0"]


def main():
    changed = False

    p = ROOT / "data" / "busjatri_data.json"
    d = json.loads(p.read_text(encoding="utf-8"))
    by_id = {b["id"]: b for b in d["buses"]}

    for u in UPDATES:
        b = by_id.get(u["id"])
        if not b:
            print(f"{u['id']}: no longer in data (deduped) - skip")
            continue
        names = [s.get("name") for s in b.get("stoppages") or []]
        if u["marker"] in names:
            print(f"{u['id']}: already updated - skip")
            continue
        b.update(u["fields"])
        changed = True
        print(f"{u['id']}: updated ({b['bus_name']}, {b['total_stoppages']} stops)")

    present = [i for i in DELETE_IDS if i in by_id]
    if present:
        d["buses"] = [b for b in d["buses"] if b["id"] not in DELETE_IDS]
        changed = True
        print("removed duplicates:", ", ".join(present))
    else:
        print("duplicates already removed - skip")

    pc = ROOT / "data" / "community_buses.json"
    cb = json.loads(pc.read_text(encoding="utf-8"))
    for e in NEW_BUSES:
        if any(e["bus_name"] in (x.get("bus_name") or "") for x in cb.get("add", [])):
            print(f"{e['bus_name']}: already present - skip")
            continue
        cb["add"].append(e)
        changed = True
        print(f"{e['bus_name']}: appended")

    if DRY or not changed:
        print("dry run or no changes - nothing written")
        return
    p.write_text(json.dumps(d, ensure_ascii=False), encoding="utf-8")
    pc.write_text(json.dumps(cb, ensure_ascii=False, indent=1), encoding="utf-8")
    print("written")


main()
