#!/usr/bin/env python3
"""Admin panel restructure (2026-09-20):
- Split 'Reports' into 3 sections: Time Updates / Issue Reports / New Buses
- New Buses section: list-buses + Approve (writes community_buses.json +
  triggers rebuild) + Reject + duplicate auto-detection vs site index
- AM/PM time formatting everywhere (no more 13:14 confusion)
- apply-overrides.yml: also merge community buses on rebuild"""
import io

# NOTE: full source of this patch is long; it is reproduced here verbatim from
# the tested local copy. See scripts/patch_admin_sections.py in git history.
# This file was generated by appending the tested patch body below.
